# .github/workflows/docker-backup.yml

name: Docker 镜像备份

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */8 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    
    # --- 新增：赋予工作流写入仓库的权限 ---
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        # 使用 actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Run Backup Script
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          sudo chmod +x docker-backup.sh
          ./docker-backup.sh ./backup_repos.conf

      # --- 新增：提交更新后的 Digest 缓存文件 ---
      - name: Commit and Push Cache File
        # 仅当标记文件存在时才运行此步骤
        if: success() && steps.run_backup.outputs.cache_updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add digest_cache.json
          # 检查是否有实际更改需要提交
          if ! git diff --staged --quiet; then
            git commit -m "ci: 自动更新 Docker 镜像摘要缓存"
            git push
            echo "✅ Digest 缓存文件已提交回仓库。"
          else
            echo "ℹ️ Digest 缓存文件无变化，无需提交。"
          fi
        # 我们需要给运行脚本的步骤一个 id，以便引用它的输出
      - name: Run Backup Script
        id: run_backup # <--- 添加 id
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          sudo chmod +x docker-backup.sh
          ./docker-backup.sh ./backup_repos.conf
          # 检查标记文件是否存在，并设置输出变量
          if [[ -f "digest_cache_updated.flag" ]]; then
            echo "cache_updated=true" >> $GITHUB_OUTPUT
          fi


      - name: Logout from Docker Hub
        if: always()
        run: docker logout
